import openai
import os
import json
import urllib3
http = urllib3.PoolManager(cert_reqs='CERT_NONE')
openai.api_key = "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"


def get_chat_answer(question, doc_content,context=None):
    print(doc_content)
    system_prompt = """Poniżej znajduje się tekst dokumentu wygenerowany przez usługę OCR. 
    Odpowiadasz na pytania tylko na podstawie tekstu dokumentu. Jeżeli informacja nie może być znaleziona w tekście odpowiedz pojedynczym słowem "BRAK"
    Jeżeli nie potrafisz odpowiedzi na pytanie na podstawie dokumentu odpowiadasz słowem <BRAK>
    """ +doc_content
    print(system_prompt)

    context_messages = []
    if context!=None:
        context_messages = [{
            "role": "assistant" if m["direction"]=='assistant' else "user",
            "content": m['message']
        } for m in context]


    messages = [{"role": "system", "content": system_prompt}] + context_messages + [ {"role": "user", "content": question}]
    print(messages)
    chat_completion = openai.ChatCompletion.create(model="gpt-3.5-turbo", messages=messages)
    api_answer =  chat_completion.choices[0].message.content
    print(api_answer)

    if (api_answer.lower()=="brak"):
        return {"status":"no_answer"}
    return {"status":"well_formed", "answer": api_answer}

if __name__ == "__main__":
    doc = """"Rzeczpospolita Polska\nDOWÓD OSOBISTY\nREPUBLIC OF POLAND / IDENTITY CARD\nNAZWISKO / SURNAME TOKARSKI\nGenerated by CamScanner from intsig. com\nIMIONA / GIVEN NAMES MACIEJ WIESŁAW\nNAZWISKO RODOWE / FAMILY NAME TOKARSKI\nIMIONA RODZICÓW/PARENTS' GIVEN NAMES WIESŁAW MAŁGORZATA\nNUMER DOWODU OSOBISTEGO/ IDENTITY CARD NUMBER\nATY429912\nlavici Takashi 28.03.1985 M DATA URODZENIA/ DATE OF BIRTH PŁEĆ / SEX\n12.07.2021\nTERMIN WAŻNOŚCI DOWODU OSOBISTEGO / EXPIRY DATE\nADRES TARELDOMIANIA / PLACE OF RESIDENCE 02-132 WARSZAWA\nNR EWIDENCYJNY PESEL PERSONAL NUMBER (PESEL)\nBALEYA S. 7 m.32\n85032808637 2021\nMEISCE URODZENIAY PLACE KIELCE\nkoloroch WZROST W CM/ HEIGHTIN CY KOLOR OCZUT COLOUR OF EYES\n182 BRAZOWE\nATY429912\nDATA WYDANIA DOWODU OSOBISTEGO/ ORGAN WYDAJĄCY DOWÓD OSOBISTY/ DATE OF ISSUE ISSUING AUTHORITY 12.07.2011 PREZYDENT M. ST. WARSZAWY DOWÓD OSOBISTY JEST DOKUMENTEM STWIERDZAJĄCYM TOŻSAMOŚĆ OSOBY ORAZ POŚWIADCZAJĄCYM OBYWATELSTWO POLSKIE\nI<POLATY4299122 <<<<<<<<<<<<<<<\n8503286M2107121POL <<<<<<<<<<< 0\nTOKARSKI << MACIEJ<WIESLAW <<<<<<\nGenerated by CamScanner from intsig. com"""

    answ = get_chat_answer("Wygeneruj jedno pytanie na które znasz odpowiedź",doc)
    print(answ)
